### ISSUE TITLE
Fucked format of multiple dates

### ISSUE THREAD

**Issue by valentinschabschneider** [deckweiss/sveltekit-i18n#2]
"{{date, date(format: shortDate)}} {{date, date(format: shortTime)}}" -> "011+0200raDaae)}} {{21aae, 21aae(f+0200r8aa"

**Comment by alexanderbetz** [comment]
Thanks @valentinschabschneider for testing this out. I fixed the issue in the mean time in v1.1.3.

**Comment by valentinschabschneider** [comment]
bruh

**Comment by alexanderbetz** [comment]
not gonna reopen this one
